export function set(path: TemplateStringsArray, ...values: any[]): any
export function concat(path: TemplateStringsArray, ...values: any[]): any
export function debounce(path: TemplateStringsArray, ...values: any[]): any
export function equals(path: TemplateStringsArray, ...values: any[]): any
export function input(path: TemplateStringsArray, ...values: any[]): any
export function merge(path: TemplateStringsArray, ...values: any[]): any
export function pop(path: TemplateStringsArray, ...values: any[]): any
export function push(path: TemplateStringsArray, ...values: any[]): any
export function shift(path: TemplateStringsArray, ...values: any[]): any
export function splice(path: TemplateStringsArray, ...values: any[]): any
export function state(path: TemplateStringsArray, ...values: any[]): any
export function unshift(path: TemplateStringsArray, ...values: any[]): any
export function wait(path: TemplateStringsArray, ...values: any[]): any
export function signal(path: TemplateStringsArray, ...values: any[]): any
export function string(path: TemplateStringsArray, ...values: any[]): any
export function toggle(path: TemplateStringsArray, ...values: any[]): any
export function unset(path: TemplateStringsArray, ...values: any[]): any
export function when(path: TemplateStringsArray, ...values: any[]): any