sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
after_success:
    - git config --global user.email "cerebraljs@gmail.com"
    - git config --global user.name "Cerebral JS"
    - npm run deploy
branches:
  only:
    - 'v3'
